version: "2"

run:
  timeout: 10m
  tests: true
  relative-path-mode: gomod
  modules-download-mode: readonly

linters:
  default: all
  exclusions:
    generated: disable
    warn-unused: true
    presets: []

  settings:
    gocyclo:
      min-complexity: 10

    godoclint:
      default: all

    revive:
      severity: error
      enable-all-rules: true
      enable-default-rules: true
      directives:
        - name: specify-disable-reason
          severity: error
      confidence: 0.1

    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false

severity:
  default: error
