version: "2"

run:
  timeout: 10m
  tests: true
  relative-path-mode: gomod
  modules-download-mode: readonly

linters:
  default: all
  disable:
    - wsl
  exclusions:
    generated: disable
    warn-unused: true
    presets: []

  settings:
    depguard:
      rules:
        Main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/mreimbold/withings-cli/internal/app
            - github.com/mreimbold/withings-cli/internal/auth
            - github.com/mreimbold/withings-cli/internal/cli
            - github.com/mreimbold/withings-cli/internal/errs
            - github.com/mreimbold/withings-cli/internal/filters
            - github.com/mreimbold/withings-cli/internal/output
            - github.com/mreimbold/withings-cli/internal/params
            - github.com/mreimbold/withings-cli/internal/services/activity
            - github.com/mreimbold/withings-cli/internal/services/api
            - github.com/mreimbold/withings-cli/internal/services/heart
            - github.com/mreimbold/withings-cli/internal/services/measures
            - github.com/mreimbold/withings-cli/internal/services/sleep
            - github.com/mreimbold/withings-cli/internal/withings
            - github.com/spf13/cobra
            - github.com/spf13/pflag

    gocyclo:
      min-complexity: 10

    godoclint:
      default: all

    revive:
      severity: error
      enable-all-rules: true
      enable-default-rules: true
      directives:
        - name: specify-disable-reason
          severity: error
      confidence: 0.1

    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false

severity:
  default: error
