version: 2

project_name: withings-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: withings-cli
    main: ./cmd/withings
    binary: withings-cli
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

universal_binaries:
  - id: withings-cli-universal
    ids:
      - withings-cli
    name_template: withings-cli
    replace: true

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_{{ if eq .Arch "all" }}universal{{ else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  prerelease: auto

brews:
  - name: withings-cli
    repository:
      owner: mreimbold
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/mreimbold/withings-cli
    description: CLI for Withings Health API
    license: MIT
    install: |
      bin.install "withings-cli"
    test: |
      system "#{bin}/withings-cli", "--version"
